parameters:
#    sil14_vitrine.example.class: sil14\VitrineBundle\Example

services:
#    sil14_vitrine.example:
#        class: %sil14_vitrine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
