parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: sil14
    database_user: sil14
    database_password: 40233
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 3fd10e2a357fc3b59cd63cbe38c4a2e939d21543
    database_path: null
