sil14_vitrine:
    resource: "@sil14VitrineBundle/Resources/config/routing.yml"
    prefix:   /
    
    
    
login:
    pattern: /login
    defaults: { _controller : sil14VitrineBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

