## YAML Template.
# src/sil14/VitrineBundle/Resources/config/doctrine/Category.orm.yml
sil14\VitrineBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: category